version: '3.8'

services:
  slack-agent:
    container_name: slack_agent
    # image: ryaneggz/slack-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped