name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  push:
    tags:
      - '*rc*'

jobs:
  ###############################################################
  ## Build Docker Image
  ###############################################################
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      (github.ref == 'refs/heads/development' || contains(github.ref, 'rc'))
    env:
      UPDATE_LATEST: ${{ github.ref == 'refs/heads/development' }}
      REPO_OWNER: ryaneggz
      REPO_NAME: slack-agent
      DOCKER_USERNAME: ryaneggz
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        # For RC tags, use the tag as is
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          # For development branch, use commit SHA
          TAG=$(echo "${{ github.sha }}" | cut -c1-7)
        fi
        
        DOCKER_IMAGE=${REPO_OWNER}/${REPO_NAME}:${TAG}
        DOCKER_LATEST=${REPO_OWNER}/${REPO_NAME}:latest
        
        echo "Building image: $DOCKER_IMAGE"
        docker build --squash -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE
        
        if [ "${UPDATE_LATEST}" = "true" ]; then
          echo "Updating latest tag"
          docker tag $DOCKER_IMAGE $DOCKER_LATEST
          docker push $DOCKER_LATEST
        fi
