name: Build Docker

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'development' }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ryaneggz
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Get short commit SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          DOCKER_IMAGE=ryaneggz/slack-agent:${COMMIT_SHORT_SHA}
          DOCKER_BRANCH_TAG=ryaneggz/slack-agent:${{ github.event.workflow_run.head_branch }}
          DOCKER_TIMESTAMP_TAG=ryaneggz/slack-agent:${TIMESTAMP}

          echo "Building images: $DOCKER_IMAGE, $DOCKER_BRANCH_TAG, $DOCKER_TIMESTAMP_TAG, and ryaneggz/slack-agent:latest"
          docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                       --cache-to=type=local,dest=/tmp/.buildx-cache \
                       --squash \
                       -t $DOCKER_IMAGE \
                       -t $DOCKER_BRANCH_TAG \
                       -t $DOCKER_TIMESTAMP_TAG \
                       -t ryaneggz/slack-agent:latest .
          docker push $DOCKER_IMAGE
          docker push $DOCKER_BRANCH_TAG
          docker push $DOCKER_TIMESTAMP_TAG
          docker push ryaneggz/slack-agent:latest

      - name: Clean up dangling Docker images
        run: docker system prune -f
