name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  ###############################################################
  ## Build Docker Image
  ###############################################################
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/development' }}
    env:
      UPDATE_LATEST: true
      REPO_OWNER: ryaneggz
      REPO_NAME: slack-response
      DOCKER_USERNAME: ryaneggz
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        COMMIT_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        DOCKER_IMAGE=${REPO_OWNER}/${REPO_NAME}:${COMMIT_SHORT_SHA}
        DOCKER_LATEST=${REPO_OWNER}/${REPO_NAME}:latest
        
        echo "Building images: $DOCKER_IMAGE and $DOCKER_LATEST"
        docker build --squash -t $DOCKER_IMAGE -t $DOCKER_LATEST .
        docker push $DOCKER_IMAGE
        if [ "${UPDATE_LATEST}" = "true" ]; then
          docker push $DOCKER_LATEST
        fi
