name: Build Docker

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'development' }}
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ryaneggz
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Get short commit SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})" >> $GITHUB_ENV

      - name: Attempt to pull Docker image
        id: pull_image
        run: |
          DOCKER_IMAGE=ryaneggz/slack-agent:${COMMIT_SHORT_SHA}
          if docker pull $DOCKER_IMAGE; then
            echo "Image $DOCKER_IMAGE exists. No need to build."
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Image $DOCKER_IMAGE does not exist. Proceeding to build."
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.IMAGE_EXISTS == 'false'
        run: |
          DOCKER_IMAGE=ryaneggz/slack-agent:${COMMIT_SHORT_SHA}
          echo "Building image: $DOCKER_IMAGE"
          docker build -t $DOCKER_IMAGE \
                       -t ryaneggz/slack-agent:latest .
          docker push $DOCKER_IMAGE
          docker push ryaneggz/slack-agent:latest

      - name: Clean up dangling Docker images
        run: docker system prune -f
