name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Debug workflow info
      run: |
        echo "Workflow run ref: ${{ github.event.workflow_run.ref }}"
        echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"

    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
        # Add host to known hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        
        # Extract tag from ref
        TAG=${GITHUB_REF#refs/tags/}
        
        
        # SSH into server and deploy
        ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "
          set -e  # Exit immediately if a command fails
          
          echo 'User: $(whoami)'
          echo 'Hostname: $(hostname)'
          echo 'OS: $(uname -a)'
          echo 'Uptime: $(uptime -p)'
          docker ps
        "
